"""
NeuraMed — Flask Prediction Server
====================================
Serves ML predictions locally (no API keys needed).

Usage:
    1. Train first: python ml/train.py
    2. Start server: python ml/server.py
    3. Server runs at http://localhost:5000

The Next.js dashboard connects to this automatically.
"""

import json
import os
import numpy as np
import joblib
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Load model and metadata
MODEL_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(MODEL_DIR, "model.joblib")
META_PATH = os.path.join(MODEL_DIR, "model_meta.json")

model = None
meta = None


def load_model():
    global model, meta
    if not os.path.exists(MODEL_PATH) or not os.path.exists(META_PATH):
        print("[FAIL] Model not found! Run 'python ml/train.py' first.")
        return False

    model = joblib.load(MODEL_PATH)
    with open(META_PATH, "r") as f:
        meta = json.load(f)
    print(f"[OK] Model loaded ({len(meta['diseases'])} diseases, {len(meta['symptoms'])} symptoms)")
    return True


@app.route("/health", methods=["GET"])
def health():
    return jsonify({
        "status": "ok",
        "model_loaded": model is not None,
        "metrics": meta["metrics"] if meta else None,
    })


@app.route("/predict", methods=["POST"])
def predict():
    if model is None or meta is None:
        return jsonify({"error": "Model not loaded"}), 500

    data = request.get_json()
    symptoms = data.get("symptoms", [])

    if not symptoms:
        return jsonify({"error": "No symptoms provided"}), 400

    # Build feature vector
    symptom_index = {name: i for i, name in enumerate(meta["symptoms"])}
    feature_vector = np.zeros(len(meta["symptoms"]))

    matched_symptoms = []
    for symptom in symptoms:
        # Case-insensitive matching
        for known_symptom, idx in symptom_index.items():
            if symptom.lower().strip() == known_symptom.lower():
                feature_vector[idx] = 1.0
                matched_symptoms.append(known_symptom)
                break

    if not matched_symptoms:
        return jsonify({"predictions": [], "message": "No recognized symptoms"})

    # Get probabilities for all diseases
    probabilities = model.predict_proba([feature_vector])[0]
    diseases = meta["diseases"]

    # Build predictions list
    predictions = []
    for i, disease_name in enumerate(diseases):
        prob = float(probabilities[i])
        if prob < 0.01:
            continue

        disease_info = meta.get("disease_info", {}).get(disease_name, {})
        severity = disease_info.get("severity", "medium")
        disease_symptoms = disease_info.get("symptoms", [])

        # Find matched symptoms for this disease
        disease_matched = [s for s in matched_symptoms if s in disease_symptoms]

        predictions.append({
            "disease": disease_name,
            "confidence": round(prob, 3),
            "severity": severity,
            "matchedSymptoms": disease_matched if disease_matched else matched_symptoms,
            "description": "",
            "precautions": [],
        })

    # Sort by confidence
    predictions.sort(key=lambda x: x["confidence"], reverse=True)

    # Generate local AI analysis
    top = predictions[0] if predictions else None
    top_names = ", ".join([p["disease"] for p in predictions[:3]])
    top_conf = int(top["confidence"] * 100) if top else 0

    severity_text = "elevated" if top and top["severity"] in ("high", "critical") else "moderate"

    ai_analysis = {
        "summary": f"Based on the symptoms ({', '.join(matched_symptoms)}), the ML model identified {top_names} as the most likely conditions. The top prediction shows {top_conf}% confidence with {severity_text} clinical significance.",
        "riskAssessment": (
            "The severity of matched conditions suggests seeking medical evaluation promptly."
            if severity_text == "elevated"
            else "Monitor symptoms and seek medical advice if they persist or worsen."
        ),
        "recommendedActions": [
            "Consult a qualified healthcare professional for proper diagnosis",
            "Document any additional symptoms or changes",
            "Avoid self-medication based solely on these results",
            "Schedule a check-up with your healthcare provider",
        ],
        "disclaimer": "This analysis is generated by the NeuraMed ML engine for educational purposes only. Always consult a qualified healthcare professional.",
    }

    return jsonify({
        "predictions": predictions[:6],
        "aiAnalysis": ai_analysis,
        "model_metrics": meta["metrics"],
    })


@app.route("/metrics", methods=["GET"])
def metrics():
    if meta is None:
        return jsonify({"error": "Model not loaded"}), 500
    return jsonify(meta["metrics"])


if __name__ == "__main__":
    print()
    print("=" * 50)
    print("  NeuraMed ML Prediction Server")
    print("=" * 50)

    if load_model():
        print(f"  Accuracy:  {meta['metrics']['accuracy']}")
        print(f"  F1 Score:  {meta['metrics']['f1_score']}")
        print(f"  Precision: {meta['metrics']['precision']}")
        print(f"  Recall:    {meta['metrics']['recall']}")
        print("=" * 50)
        print("  Starting server on http://localhost:5000")
        print("=" * 50)
        print()
        app.run(host="0.0.0.0", port=5000, debug=False)
    else:
        print("\nRun 'python ml/train.py' first to train the model.")
