// ─────────────────────────────────────────
// AI Analysis Module
// Uses Groq API if available, otherwise generates local analysis
// ─────────────────────────────────────────

export interface AIAnalysis {
    summary: string;
    riskAssessment: string;
    recommendedActions: string[];
    disclaimer: string;
}

interface PredictionInput {
    disease: string;
    confidence: number;
    severity: string;
    matchedSymptoms: string[];
}

// ── Local Analysis (no API needed) ────────

function generateLocalAnalysis(
    symptoms: string[],
    predictions: PredictionInput[]
): AIAnalysis {
    const top = predictions[0];
    const topDiseases = predictions
        .slice(0, 3)
        .map((p) => p.disease)
        .join(", ");

    const severityLevel =
        top?.severity === "critical" || top?.severity === "high"
            ? "elevated"
            : "moderate";

    const confidencePercent = top ? Math.round(top.confidence * 100) : 0;

    return {
        summary: `Based on the reported symptoms (${symptoms.join(", ")}), the analysis engine identified potential matches including ${topDiseases}. The top match shows a ${confidencePercent}% confidence level with ${severityLevel} clinical significance.`,
        riskAssessment:
            severityLevel === "elevated"
                ? "The severity level of the top matched conditions suggests prompt medical evaluation. Please consult a healthcare provider for proper diagnosis."
                : "The matched conditions show moderate severity. Monitor your symptoms and seek medical advice if they persist or worsen.",
        recommendedActions: [
            "Consult a qualified healthcare professional for proper diagnosis",
            "Document any additional symptoms or changes in condition",
            "Avoid self-medication based solely on these results",
            top?.severity === "critical" || top?.severity === "high"
                ? "Consider seeking immediate medical attention if symptoms worsen"
                : "Schedule a routine check-up with your healthcare provider",
        ],
        disclaimer:
            "This analysis is generated by the NeuraMed prediction engine for educational purposes only. It does not constitute medical advice. Always consult a qualified healthcare professional for diagnosis and treatment.",
    };
}

// ── Groq AI Analysis (optional) ───────────

async function analyzeWithGroq(
    symptoms: string[],
    predictions: PredictionInput[]
): Promise<AIAnalysis | null> {
    if (!process.env.GROQ_API_KEY) return null;

    try {
        const { default: Groq } = await import("groq-sdk");
        const client = new Groq({ apiKey: process.env.GROQ_API_KEY });

        const topPredictions = predictions.slice(0, 3);
        const predictionsContext = topPredictions
            .map(
                (p, i) =>
                    `${i + 1}. ${p.disease} (${Math.round(p.confidence * 100)}% confidence, ${p.severity} severity) — matched symptoms: ${p.matchedSymptoms.join(", ")}`
            )
            .join("\n");

        const completion = await client.chat.completions.create({
            model: "llama-3.3-70b-versatile",
            messages: [
                {
                    role: "system",
                    content: `You are NeuraMed AI, a medical analysis assistant. Respond in exact JSON format:
{"summary":"...","riskAssessment":"...","recommendedActions":["...","...","...","..."],"disclaimer":"This AI analysis is for educational purposes only."}`,
                },
                {
                    role: "user",
                    content: `Analyze: Symptoms: ${symptoms.join(", ")}. Predictions:\n${predictionsContext}`,
                },
            ],
            temperature: 0.3,
            max_tokens: 600,
            response_format: { type: "json_object" },
        });

        const content = completion.choices[0]?.message?.content;
        if (!content) return null;

        const parsed = JSON.parse(content) as AIAnalysis;
        if (!parsed.summary || !parsed.riskAssessment) return null;

        parsed.disclaimer =
            "This AI analysis is for educational purposes only and does not constitute medical advice. Always consult a qualified healthcare professional for diagnosis and treatment.";
        return parsed;
    } catch (err) {
        console.warn("[Groq] AI analysis failed, using local fallback:", err);
        return null;
    }
}

// ── Main Export ───────────────────────────

export async function analyzeSymptoms(
    symptoms: string[],
    predictions: PredictionInput[]
): Promise<AIAnalysis> {
    // Try Groq first, fall back to local analysis
    const groqResult = await analyzeWithGroq(symptoms, predictions);
    if (groqResult) return groqResult;

    return generateLocalAnalysis(symptoms, predictions);
}
