"""
NeuraMed — Module Registry
Central metadata for all 6 imaging modules.
"""

MODULE_META = {
    "brain_tumor": {
        "label":        "Brain Tumor",
        "icon":         "brain",
        "modality":     "MRI",
        "classes":      ["No Tumor", "Glioma", "Meningioma", "Pituitary Tumor"],
        "num_classes":  4,
        "input_size":   [224, 224],
        "backbone":     "EfficientNet-B3",
        "dataset":      "Kaggle Brain Tumor MRI",
        "dataset_size": 7023,
    },
    "alzheimers": {
        "label":        "Alzheimer's",
        "icon":         "microscope",
        "modality":     "MRI",
        "classes":      ["Non Demented", "Very Mild Dementia", "Mild Dementia", "Moderate Dementia"],
        "num_classes":  4,
        "input_size":   [176, 176],
        "backbone":     "EfficientNet-B3",
        "dataset":      "ADNI + Kaggle Alzheimer MRI",
        "dataset_size": 6400,
    },
    "lung_disease": {
        "label":        "Lung Disease",
        "icon":         "lungs",
        "modality":     "Chest X-Ray",
        "classes":      ["Normal", "Pneumonia", "Lung Cancer", "Tuberculosis"],
        "num_classes":  4,
        "input_size":   [256, 256],
        "backbone":     "EfficientNet-B3",
        "dataset":      "NIH ChestX-ray14 + PadChest",
        "dataset_size": 112120,
    },
    "lumbar_spine": {
        "label":        "Lumbar Spine",
        "icon":         "bone",
        "modality":     "X-Ray / MRI",
        "classes":      ["Normal", "Disc Herniation", "Spondylosis", "Spinal Stenosis"],
        "num_classes":  4,
        "input_size":   [224, 224],
        "backbone":     "EfficientNet-B3",
        "dataset":      "SpineWeb + VGH Lumbar MRI",
        "dataset_size": 4200,
    },
    "neuroimaging": {
        "label":        "Neuroimaging",
        "icon":         "zap",
        "modality":     "CT / MRI",
        "classes":      ["Normal", "Ischemic Stroke", "Multiple Sclerosis", "Intracranial Hemorrhage"],
        "num_classes":  4,
        "input_size":   [256, 256],
        "backbone":     "EfficientNet-B3",
        "dataset":      "ISLES 2022 + MICCAI MS Lesion",
        "dataset_size": 3800,
    },
    "covid_xray": {
        "label":        "COVID-19 X-Ray",
        "icon":         "virus",
        "modality":     "Chest X-Ray",
        "classes":      ["Normal", "COVID-19", "Viral Pneumonia", "Bacterial Pneumonia"],
        "num_classes":  4,
        "input_size":   [256, 256],
        "backbone":     "EfficientNet-B3",
        "dataset":      "COVID-19 Radiography Database",
        "dataset_size": 21165,
    },
}
